version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # เปลี่ยน port ตามความเหมาะสม
    volumes:
      - .:/app
    command: npm start
